spring.application.name=tareas
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${SPRING_DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATABASE_USERNAME}
spring.datasource.password=${SPRING_DATABASE_PASSWORD}
server.port=8080
amazon.dynamodb.endpoint=${DYNAMODB_ENDPOINT}
amazon.dynamodb.region=${DYNAMODB_REGION}
amazon.dynamodb.accesskey=${DYNAMODB_ACCESS_KEY}
amazon.dynamodb.secretkey=${DYNAMODB_SECRET_KEY}
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB