package com.grupo5.tareas.api.cckphistoricaldata;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "cckp_historical_data")
public class CckpHistoricalData {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "year")
    private String year;

    @DynamoDBAttribute(attributeName = "month")
    private String month;

    @DynamoDBAttribute(attributeName = "precipitacion")
    private String precipitacion;

    @DynamoDBAttribute(attributeName = "temperatura")
    private String temperatura;

}
