package com.grupo5.tareas.api.files;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "tareas")
public class File {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "assignment_id")
    private String assignmentId;

    @DynamoDBAttribute(attributeName = "file_name")
    private String fileName;

    @DynamoDBAttribute(attributeName = "file_url")
    private String fileUrl;

    @DynamoDBAttribute(attributeName = "file_type")
    private String fileType;

    @DynamoDBAttribute(attributeName = "uploaded_at")
    private String uploadedAt;

}
